<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Jorge Cimentada" />

<meta name="date" content="2017-07-31" />

<title>Calculating percentile differences from ordered categorical and continuous variables</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>



<link href="data:text/css;charset=utf-8,body%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Amargin%3A%201em%20auto%3B%0Amax%2Dwidth%3A%20700px%3B%0Aoverflow%3A%20visible%3B%0Apadding%2Dleft%3A%202em%3B%0Apadding%2Dright%3A%202em%3B%0Afont%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0Afont%2Dsize%3A%2014px%3B%0Aline%2Dheight%3A%201%2E35%3B%0A%7D%0A%23header%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0A%23TOC%20%7B%0Aclear%3A%20both%3B%0Amargin%3A%200%200%2010px%2010px%3B%0Apadding%3A%204px%3B%0Awidth%3A%20400px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Aborder%2Dradius%3A%205px%3B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Afont%2Dsize%3A%2013px%3B%0Aline%2Dheight%3A%201%2E3%3B%0A%7D%0A%23TOC%20%2Etoctitle%20%7B%0Afont%2Dweight%3A%20bold%3B%0Afont%2Dsize%3A%2015px%3B%0Amargin%2Dleft%3A%205px%3B%0A%7D%0A%23TOC%20ul%20%7B%0Apadding%2Dleft%3A%2040px%3B%0Amargin%2Dleft%3A%20%2D1%2E5em%3B%0Amargin%2Dtop%3A%205px%3B%0Amargin%2Dbottom%3A%205px%3B%0A%7D%0A%23TOC%20ul%20ul%20%7B%0Amargin%2Dleft%3A%20%2D2em%3B%0A%7D%0A%23TOC%20li%20%7B%0Aline%2Dheight%3A%2016px%3B%0A%7D%0Atable%20%7B%0Amargin%3A%201em%20auto%3B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dcolor%3A%20%23DDDDDD%3B%0Aborder%2Dstyle%3A%20outset%3B%0Aborder%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0Aborder%2Dwidth%3A%202px%3B%0Apadding%3A%205px%3B%0Aborder%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dstyle%3A%20inset%3B%0Aline%2Dheight%3A%2018px%3B%0Apadding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0Aborder%2Dleft%2Dstyle%3A%20none%3B%0Aborder%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Ap%20%7B%0Amargin%3A%200%2E5em%200%3B%0A%7D%0Ablockquote%20%7B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Apadding%3A%200%2E25em%200%2E75em%3B%0A%7D%0Ahr%20%7B%0Aborder%2Dstyle%3A%20solid%3B%0Aborder%3A%20none%3B%0Aborder%2Dtop%3A%201px%20solid%20%23777%3B%0Amargin%3A%2028px%200%3B%0A%7D%0Adl%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Adl%20dd%20%7B%0Amargin%2Dbottom%3A%2013px%3B%0Amargin%2Dleft%3A%2013px%3B%0A%7D%0Adl%20dt%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Aul%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Aul%20li%20%7B%0Alist%2Dstyle%3A%20circle%20outside%3B%0A%7D%0Aul%20ul%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Apre%2C%20code%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0Acolor%3A%20%23333%3B%0Awhite%2Dspace%3A%20pre%2Dwrap%3B%20%0A%7D%0Apre%20%7B%0Aborder%2Dradius%3A%203px%3B%0Amargin%3A%205px%200px%2010px%200px%3B%0Apadding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0Afont%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0Apadding%3A%202px%200px%3B%0A%7D%0Adiv%2Efigure%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0Abackground%2Dcolor%3A%20%23FFFFFF%3B%0Apadding%3A%202px%3B%0Aborder%3A%201px%20solid%20%23DDDDDD%3B%0Aborder%2Dradius%3A%203px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Amargin%3A%200%205px%3B%0A%7D%0Ah1%20%7B%0Amargin%2Dtop%3A%200%3B%0Afont%2Dsize%3A%2035px%3B%0Aline%2Dheight%3A%2040px%3B%0A%7D%0Ah2%20%7B%0Aborder%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Apadding%2Dbottom%3A%202px%3B%0Afont%2Dsize%3A%20145%25%3B%0A%7D%0Ah3%20%7B%0Aborder%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Afont%2Dsize%3A%20120%25%3B%0A%7D%0Ah4%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0Amargin%2Dleft%3A%208px%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Ah5%2C%20h6%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23ccc%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%230033dd%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%20%7B%0Acolor%3A%20%236666ff%3B%20%7D%0Aa%3Avisited%20%7B%0Acolor%3A%20%23800080%3B%20%7D%0Aa%3Avisited%3Ahover%20%7B%0Acolor%3A%20%23BB00BB%3B%20%7D%0Aa%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0Aa%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%20code%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%0A" rel="stylesheet" type="text/css" />

</head>

<body>




<h1 class="title toc-ignore">Calculating percentile differences from ordered categorical and continuous variables</h1>
<h4 class="author"><em>Jorge Cimentada</em></h4>
<h4 class="date"><em>2017-07-31</em></h4>



<p>Reardon (2011) introduced a very interesting concept in which he calculates percentile differences from ordered categorical variables. He explains his procedure very much in detail in the appendix of the book chapter but no formal implementation has been yet available on the web. With this package I introduce a function that applies the proceedure, following a step-by-step Stata script that Sean Reardon kindly sent me.</p>
<p>In this vignette I show you how to use the function and match the results to the Stata code provided by Reardon himself.</p>
<p>For this example, we’ll use a real world data set, one I’m very much familiar with: PISA. We’ll use the PISA 2012 wave for Germany because it asked parents about their income category. For this example we’ll need the packages below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># install.packages(c(&quot;devtools&quot;, &quot;matrixStats&quot;, &quot;tidyverse&quot;))</span>
<span class="co"># devtools::install_github(&quot;pbiecek/PISA2012lite&quot;)</span>

<span class="kw">library</span>(matrixStats)
<span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(haven)
<span class="kw">library</span>(PISA2012lite)</code></pre></div>
<p>If you haven’t installed any of the packages above, uncomment the first two lines to install them. Beware that the <code>PISA2012lite</code> package contains the PISA 2012 data and takes a while to download.</p>
<p>Let’s prepare the data. Below we filter only German students, select only the math test results and calculate the median of all math plausible values to get one single math score. Finally, we match each student with their corresponding income data from their parents data and their sample weights.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ger_student &lt;-<span class="st"> </span>student2012 %&gt;%
<span class="st">  </span><span class="kw">filter</span>(CNT ==<span class="st"> &quot;Germany&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">select</span>(CNT, STIDSTD, <span class="kw">matches</span>(<span class="st">&quot;^PV*.MATH$&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">transmute</span>(CNT, STIDSTD,
            <span class="dt">avg_score =</span> <span class="kw">rowMeans</span>(student2012[student2012$CNT ==<span class="st"> &quot;Germany&quot;</span>, <span class="kw">paste0</span>(<span class="st">&quot;PV&quot;</span>, <span class="dv">1</span>:<span class="dv">5</span>, <span class="st">&quot;MATH&quot;</span>)]))

ger_parent &lt;-
<span class="st">  </span>parent2012 %&gt;%
<span class="st">  </span><span class="kw">filter</span>(CNT ==<span class="st"> &quot;Germany&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">select</span>(CNT, STIDSTD, PA07Q01)

ger_weights &lt;-
<span class="st">  </span>student2012weights %&gt;%
<span class="st">  </span><span class="kw">filter</span>(CNT ==<span class="st"> &quot;Germany&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">select</span>(CNT, STIDSTD, W_FSTUWT)

dataset_ready &lt;-
<span class="st">  </span>ger_student %&gt;%
<span class="st">  </span><span class="kw">left_join</span>(ger_parent, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;CNT&quot;</span>, <span class="st">&quot;STIDSTD&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">left_join</span>(ger_weights, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;CNT&quot;</span>, <span class="st">&quot;STIDSTD&quot;</span>)) %&gt;%
<span class="st">  </span><span class="kw">as_tibble</span>() %&gt;%
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">income =</span> PA07Q01,
         <span class="dt">score =</span> avg_score,
         <span class="dt">wt =</span> W_FSTUWT) %&gt;%
<span class="st">  </span><span class="kw">select</span>(-CNT, -STIDSTD)</code></pre></div>
<p>The final results is this dataset:</p>
<pre><code>## # A tibble: 10 x 3
##       score         income       wt
##       &lt;dbl&gt;         &lt;fctr&gt;    &lt;dbl&gt;
##  1 439.5622 Less than &lt;$A&gt; 137.3068
##  2 523.1422 Less than &lt;$A&gt; 170.0566
##  3 291.4083 Less than &lt;$A&gt; 162.3794
##  4 436.6023 Less than &lt;$A&gt; 162.3794
##  5 367.4326 Less than &lt;$A&gt; 114.6644
##  6 369.6136 Less than &lt;$A&gt; 121.8309
##  7 506.0835 Less than &lt;$A&gt; 128.1200
##  8 563.4912 Less than &lt;$A&gt; 128.1200
##  9 479.8333 Less than &lt;$A&gt; 117.0752
## 10 557.4934 Less than &lt;$A&gt; 117.8207</code></pre>
<p>This is the minimum dataset that the function will accept. This means that it needs to have at least a categorical variable and a continuous variable (the vector of weights is optional).</p>
<p>The package is called <code>perccalc</code>, short for percentile calculator and we can install and load it with this code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">devtools::<span class="kw">install_github</span>(<span class="st">&quot;cimentadaj/perccalc&quot;</span>)
<span class="kw">library</span>(perccalc)</code></pre></div>
<p>The package only has one function called <code>perc_calculator</code> and it’s very easy to use, we just specify the data, the name of the categorical and continuous variable and the percentile difference we want.</p>
<p>Let’s put it to use!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">perc_calculator</span>(dataset_ready, income, score, <span class="dt">percentiles =</span> <span class="kw">c</span>(<span class="dv">90</span>, <span class="dv">10</span>))</code></pre></div>
<pre><code>## difference         se 
##   97.00706    8.74790</code></pre>
<p>I generated that error on purpose to raise a very important requirement of the function. The categorical variable needs to be an ordered factor (categorical). It is very important because otherwise we could be calculating percentile differences of categorical variables such as married, single and widowed, which doesn’t make a lot of sense.</p>
<p>We can turn it into an ordered factor with the code below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dataset_ready &lt;-
<span class="st">  </span>dataset_ready %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">income =</span> <span class="kw">factor</span>(income, <span class="dt">ordered =</span> <span class="ot">TRUE</span>))</code></pre></div>
<p>Now it’ll work.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">perccalc::<span class="kw">perc_calculator</span>(dataset_ready, income, score, <span class="dt">percentiles =</span> <span class="kw">c</span>(<span class="dv">90</span>, <span class="dv">10</span>))</code></pre></div>
<pre><code>## difference         se 
##   97.00706    8.74790</code></pre>
<p>We can play around with other percentiles</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">perccalc::<span class="kw">perc_calculator</span>(dataset_ready, income, score, <span class="dt">percentiles =</span> <span class="kw">c</span>(<span class="dv">50</span>, <span class="dv">10</span>))</code></pre></div>
<pre><code>## difference         se 
##  58.776200   8.291083</code></pre>
<p>And we can add a vector of weights</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">perccalc::<span class="kw">perc_calculator</span>(dataset_ready, income, score, <span class="dt">weights =</span> wt, <span class="dt">percentiles =</span> <span class="kw">c</span>(<span class="dv">90</span>, <span class="dv">10</span>))</code></pre></div>
<pre><code>## difference         se 
##  95.220358   8.451136</code></pre>
<p>Now, how are we sure that these estimates are as accurate as the Reardon (2011) implementation? We can compare the Stata ouput using this data set.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Saving the dataset to a path</span>
dataset_ready %&gt;%
<span class="st">  </span><span class="kw">write_dta</span>(<span class="dt">path =</span> <span class="st">&quot;/Users/cimentadaj/Downloads/pisa_income.dta&quot;</span>, <span class="dt">version =</span> <span class="dv">13</span>)</code></pre></div>
<p>Running the code below using the <code>pisa_income.dta</code>..</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">*--------
use <span class="st">&quot;/Users/cimentadaj/Downloads/pisa_income.dta&quot;</span>, clear

tab income, <span class="kw">gen</span>(inc)
*--------

<span class="er">/*</span>-----------------------
<span class="st">    </span>Making a data set that has 
    one observation per income category
    and has mean and <span class="kw">se</span>(mean) in each category
    and percent of population in the category
------------------------<span class="er">*/</span>

tempname memhold
tempfile results
postfile <span class="st">`</span><span class="dt">memhold' income mean se_mean per using </span><span class="st">`</span>results<span class="st">'</span>

<span class="st">forv i = 1/6 {</span>
<span class="st">    qui sum inc`i'</span> [aw=wt]
    loc per<span class="st">`</span><span class="dt">i' = r(mean)    </span>
<span class="dt">                                </span>
<span class="dt">    qui sum score if inc</span><span class="st">`</span>i<span class="st">'==1 </span>
<span class="st">                            </span>
<span class="st">    if `r(N)'</span>&gt;<span class="dv">0</span> {
        qui regress score if inc<span class="st">`</span><span class="dt">i'==1 [aw=wt]</span>
<span class="dt">        post </span><span class="st">`</span>memhold<span class="st">' (`i'</span><span class="er">)</span> (_b[_cons]) (_se[_cons]) (<span class="st">`</span><span class="dt">per</span><span class="st">`</span>i<span class="st">''</span>)
                            
    }               
<span class="er">}</span>
postclose <span class="st">`</span><span class="dt">memhold' </span>

<span class="dt">/*-----------------------</span>
<span class="dt">    Making income categories</span>
<span class="dt">    into percentiles</span>
<span class="dt">------------------------*/</span>


<span class="dt">    use </span><span class="st">`</span>results<span class="st">', clear</span>

<span class="st">    sort income</span>
<span class="st">    gen cathi = sum(per)</span>
<span class="st">    gen catlo = cathi[_n-1]</span>
<span class="st">    replace catlo = 0 if income==1</span>
<span class="st">    gen catmid = (catlo+cathi)/2</span>
<span class="st">    </span>
<span class="st">    /*-----------------------</span>
<span class="st">        Calculate income </span>
<span class="st">        achievement gaps</span>
<span class="st">    ------------------------*/</span>

<span class="st">    sort income</span>
<span class="st">    </span>
<span class="st">    g x1 = catmid</span>
<span class="st">    g x2 = catmid^2 + ((cathi-catlo)^2)/12</span>
<span class="st">    g x3 = catmid^3 + ((cathi-catlo)^2)/4</span>

<span class="st">    g cimnhi = mean + 1.96*se_mean</span>
<span class="st">    g cimnlo = mean - 1.96*se_mean</span>

<span class="st">    reg mean x1 x2 x3 [aw=1/se_mean^2] </span>

<span class="st">    twoway (rcap cimnhi cimnlo catmid) (scatter mean catmid) ///</span>
<span class="st">        (function y = _b[_cons] + _b[x1]*x + _b[x2]*x^2 + _b[x3]*x^3, ran(0 1)) </span>
<span class="st">    </span>
<span class="st">    loc hi_p = 90</span>
<span class="st">    loc lo_p = 10</span>

<span class="st">    loc d1 = [`hi_p'</span> -<span class="st"> `</span><span class="dt">lo_p']/100</span>
<span class="dt">    loc d2 = [(</span><span class="st">`</span>hi_p<span class="st">')^2 - (`lo_p'</span><span class="er">)</span>^<span class="dv">2</span>]/(<span class="dv">100</span>^<span class="dv">2</span>)
    loc d3 =<span class="st"> </span>[(<span class="st">`</span><span class="dt">hi_p')^3 - (</span><span class="st">`</span>lo_p<span class="st">')^3]/(100^3)</span>

<span class="st">    lincom `d1'</span>*x1 +<span class="st"> `</span><span class="dt">d2'*x2 + </span><span class="st">`</span>d3<span class="st">'*x3</span>
<span class="st">    loc diff`hi_p'`</span><span class="dt">lo_p' = r(estimate)</span>
<span class="dt">    loc se</span><span class="st">`</span>hi_p<span class="st">'`lo_p'</span> =<span class="st"> </span><span class="kw">r</span>(se)
    
    di <span class="st">&quot;`hi_p'-`lo_p' gap:     `diff`hi_p'`lo_p''&quot;</span>
    di <span class="st">&quot;se(`hi_p'-`lo_p' gap): `se`hi_p'`lo_p''&quot;</span></code></pre></div>
<p>I get that the 90/10 difference is <code>95.22</code> with a standard error of <code>8.45</code>. Does it sound familiar?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">perc_calculator</span>(dataset_ready, income, score, <span class="dt">weights =</span> wt, <span class="dt">percentiles =</span> <span class="kw">c</span>(<span class="dv">90</span>, <span class="dv">10</span>))</code></pre></div>
<pre><code>## difference         se 
##  95.220358   8.451136</code></pre>
<p>I hope this was a convincing example, I know this will be useful for me. All the intelectual ideas come from Sean Reardon, as well as the Stata code. The R implemention is my own work.</p>
<ul>
<li>Reardon, Sean F. “The widening academic achievement gap between the rich and the poor: New evidence and possible explanations.” Whither opportunity (2011): 91-116.</li>
</ul>



<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
